### ISSUE TITLE
Ability to pass a proxy to ClientFactory.Create

### ISSUE THREAD

**Issue by da3dsoul** [maxpiva/Nancy.Rest.Client#1]
This would make debugging so much easier....

**Comment by da3dsoul** [comment]
It'd take like 15 minutes tops. I don't want to touch that code since you've supposedly been working on it...that and I'm not confident in my network programming.

**Comment by maxpiva** [comment]
Will do

**Comment by maxpiva** [comment]
Done in 1.4.4.6
